#!/usr/bin/env python3
import json
import re

# Read the new flashcards
with open('smart_flashcards.json', 'r') as f:
    new_flashcards = json.load(f)

# Read the current flashcards-data.js file
with open('docs/static/flashcards-data.js', 'r') as f:
    content = f.read()

# Extract the FLASHCARD_DATA object as JSON
# Find the start and end of the JSON object
start_marker = 'const FLASHCARD_DATA = '
start_idx = content.find(start_marker) + len(start_marker)
end_idx = content.rfind('};') + 1

json_str = content[start_idx:end_idx]
current_data = json.loads(json_str)

# Count additions
total_added = 0
category_stats = []

# Add new flashcards to each category
for category in current_data['categories']:
    category_name = category['name']

    if category_name in new_flashcards:
        new_cards = new_flashcards[category_name]
        current_count = len(category['flashcards'])

        # Add each new card with simple formatting
        for card in new_cards:
            formatted_card = {
                'question': card['question'],
                'answer': card['answer']
            }
            category['flashcards'].append(formatted_card)
            total_added += 1

        new_count = len(category['flashcards'])
        category_stats.append(f"{category_name}: {current_count} → {new_count} (+{len(new_cards)})")

# Update metadata
current_data['metadata']['totalCards'] = sum(len(cat['flashcards']) for cat in current_data['categories'])

# Convert back to JavaScript
new_content = f"""// Flashcard data - embedded for GitHub Pages compatibility
// Auto-generated by build_static.py - DO NOT EDIT DIRECTLY
// Edit flashcards-enhanced.json instead, then run: python3 build_static.py

const FLASHCARD_DATA = {json.dumps(current_data, indent=2)};
"""

# Write the updated file
with open('docs/static/flashcards-data.js', 'w') as f:
    f.write(new_content)

print(f"\n✓ Successfully updated flashcards-data.js")
print(f"\nCategory updates:")
for stat in category_stats:
    print(f"  {stat}")
print(f"\nTotal cards added: {total_added}")
print(f"New total: {current_data['metadata']['totalCards']}")
