#!/usr/bin/env python3
"""
Generate docs/static/flashcards-data.js from flashcards.db

This script reads flashcard data from the SQLite database and creates
a JavaScript file that can be used by the flashcard web application.
"""

import sqlite3
import json
from datetime import datetime
from pathlib import Path

def main():
    # Database path
    db_path = Path(__file__).parent / "flashcards.db"

    # Output file path
    output_path = Path(__file__).parent.parent / "docs" / "static" / "flashcards-data.js"

    # Connect to database
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Get all categories
    cursor.execute("SELECT id, name FROM categories ORDER BY name")
    categories = cursor.fetchall()

    # Build the data structure
    flashcard_data = {
        "metadata": {
            "title": "Jeopardy Study Flashcards",
            "description": "Flashcard set from Jeopardy questions",
            "totalCards": 0,
            "categories": len(categories)
        },
        "categories": []
    }

    total_cards = 0

    # For each category, get its flashcards
    for category_id, category_name in categories:
        cursor.execute("""
            SELECT question, answer
            FROM flashcards
            WHERE category_id = ?
            ORDER BY id
        """, (category_id,))

        flashcards = []
        for question, answer in cursor.fetchall():
            flashcards.append({
                "question": question,
                "answer": answer
            })
            total_cards += 1

        # Only add category if it has flashcards
        if flashcards:
            flashcard_data["categories"].append({
                "name": category_name,
                "flashcards": flashcards
            })

    # Update total cards count
    flashcard_data["metadata"]["totalCards"] = total_cards
    flashcard_data["metadata"]["categories"] = len(flashcard_data["categories"])

    # Generate JavaScript file
    js_content = f"""// Flashcard data - embedded for GitHub Pages compatibility
// Auto-generated by generate_flashcards_js.py - DO NOT EDIT DIRECTLY
// Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

const FLASHCARD_DATA = {json.dumps(flashcard_data, indent=2, ensure_ascii=False)};
"""

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    # Close database
    conn.close()

    # Print summary
    print(f"✓ Generated {output_path}")
    print(f"  Total categories: {flashcard_data['metadata']['categories']}")
    print(f"  Total flashcards: {flashcard_data['metadata']['totalCards']}")
    print(f"\nFlashcards per category:")
    for category in flashcard_data["categories"]:
        print(f"  - {category['name']}: {len(category['flashcards'])} cards")

if __name__ == "__main__":
    main()
