#!/usr/bin/env python3
"""
Build Static Flashcards - Converts JSON to JS for GitHub Pages

This script takes flashcards-enhanced.json and creates flashcards-data.js
for the static version that works without a server.

Usage:
    python3 build_static.py
"""

import json
import os

def build_static():
    """Convert JSON flashcards to JS format for static hosting."""

    # File paths
    json_file = "local_server/flashcards-enhanced.json"
    js_file = "static/flashcards-data.js"

    # Check if JSON file exists
    if not os.path.exists(json_file):
        print(f"❌ Error: {json_file} not found!")
        print("   Make sure you're running this from the study_guide/ directory")
        print("   and that local_server/ folder exists with flashcards-enhanced.json")
        return False

    # Read JSON file
    print(f"📖 Reading {json_file}...")
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Count flashcards
    total_cards = sum(len(cat['flashcards']) for cat in data['categories'])
    print(f"✓ Loaded {total_cards} flashcards across {len(data['categories'])} categories")

    # Create static directory if it doesn't exist
    os.makedirs("static", exist_ok=True)

    # Write JS file
    print(f"📝 Writing {js_file}...")
    with open(js_file, 'w', encoding='utf-8') as f:
        f.write("// Flashcard data - embedded for GitHub Pages compatibility\n")
        f.write("// Auto-generated by build_static.py - DO NOT EDIT DIRECTLY\n")
        f.write("// Edit flashcards-enhanced.json instead, then run: python3 build_static.py\n\n")
        f.write("const FLASHCARD_DATA = ")
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    # Get file sizes
    json_size = os.path.getsize(json_file) / 1024  # KB
    js_size = os.path.getsize(js_file) / 1024  # KB

    print(f"✓ Created {js_file}")
    print(f"  JSON file: {json_size:.1f}KB")
    print(f"  JS file:   {js_size:.1f}KB")
    print(f"\n✅ Done! Static version ready for GitHub Pages")
    print(f"\nNext steps:")
    print(f"  1. Open static/flashcards.html to test")
    print(f"  2. Git add/commit/push static/ folder to GitHub Pages")
    print(f"\nWorkflow:")
    print(f"  • Edit: local_server/flashcards-enhanced.json")
    print(f"  • Run: python3 build_static.py")
    print(f"  • Deploy: Push static/ folder")

    return True

if __name__ == "__main__":
    print("🎯 Building Static Flashcards for GitHub Pages\n")
    success = build_static()
    exit(0 if success else 1)
